version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - unzip install/terraform_1.0.9_linux_amd64.zip -d /usr/bin
  build:
    commands:
      - terraform init
      - terraform apply
artifacts:
  files: 
    - package.zip